In [4]:
#HW Exercise 1: Write a Python function which will sum all the following listed items (5,8,2,4,7,9)
def sumoflist(a,b,c,d,e,f):
    return a+b+c+d+e+f
sumoflist(5,8,2,4,7,9)

35

In [5]:
#HW Exercise 2: Write a Python function whihc will find the product/multiply the items in the following list: (4,3,5,6,2)
def productoflist(a,b,c,d,e):
    return a*b*c*d*e
productoflist(4,3,5,6,2)

720

In [30]:
#HW Exercise: Given the following array:
#Using numpy:
#a) Sort the flattened array
#b) Sort the second column
#c) Sort the third row
#d) Extract the second row onwards
#e) Extract the third column onwards
#f) obtain the square of array_hw
#g)Slice the element from the third row and fourth column position 3X4
#f) obtain the total sum of array_hw
#h) How many dimentions does array_hw have?
#i) What is the data type listed in array_hw?
#j) What is the size of the memory in bytes consumed by all the elements in array_hw?
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
#a)
print("a) ",np.sort(array_hw.flatten()))
#b)
print("b) ",np.sort(array_hw,axis=0)[...,1])
#c)
print("c) ",np.sort(array_hw,axis=1)[2,...])
#d)
print("d) ", array_hw[1,...])
#e)
print("e) ",array_hw[...,2])
#f)
print("f)",array_hw**2)
#g)
print("g)",array_hw[2,3])
#f) You have 2 fs professor
print("f) ",array_hw.sum())
#h)
print("h) ",array_hw.shape)
#i)
print("i) ",array_hw.dtype)
#j
print("j) ", array_hw.nbytes)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
a)  [1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]
b)  [5 7 7 9]
c)  [2 4 6 7 8 8]
d)  [7 7 5 3 5 7]
e)  [8 5 8 7]
f) [[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]
g) 4
f)  145
h)  (4, 6)
i)  int32
j)  96
